name: Migrate
on: [push, pull_request]
permissions:
  contents: read
jobs:
  migrate:
    strategy:
      fail-fast: false
      matrix:
        include:
          - tests: 7.9.3-latest
            node-version: 16.20.2
            generate-command: npx --yes generator-jhipster@7.9.3 --defaults
            migrate-command: jhipster-migrate
          - tests: 7.9.3-latest (skip-dependencies)
            node-version: 16.20.2
            generate-command: npx --yes generator-jhipster@7.9.3 --defaults --skip-jhipster-dependencies
            migrate-command: jhipster-migrate
          - tests: 7.8.1-7.9.3
            node-version: 16.20.2
            generate-command: npx --yes generator-jhipster@7.8.1 --defaults
            migrate-command: jhipster-migrate --target-version 7.9.3
          - tests: 7.9.3-7.9.4
            node-version: 16.20.2
            generate-command: npx --yes generator-jhipster@7.9.3 --defaults
            migrate-command: jhipster-migrate --target-version 7.9.4
          - tests: 8.1.0-latest
            node-version: 20
            generate-command: npx --yes generator-jhipster@8.1.0 --defaults
            migrate-command: jhipster-migrate
          - tests: 8.2.1-latest
            node-version: 20
            generate-command: npx --yes generator-jhipster@8.2.1 --defaults
            migrate-command: jhipster-migrate
          - tests: j8.3.0
            node-version: 20
            generate-command: npx --yes generator-jhipster@8.3.0 --defaults
            migrate-command: jhipster-migrate
          - tests: j8.4.0
            node-version: 20
            generate-command: npx --yes generator-jhipster@8.4.0 --defaults
            migrate-command: jhipster-migrate
          - tests: j8.5.0
            node-version: 20
            generate-command: npx --yes generator-jhipster@8.5.0 --defaults
            migrate-command: jhipster-migrate
          - tests: j8.6.0
            node-version: 20
            generate-command: npx --yes generator-jhipster@8.6.0 --defaults
            migrate-command: jhipster-migrate
          - tests: j8.7.0
            node-version: 20
            generate-command: npx --yes generator-jhipster@8.7.0 --defaults
            migrate-command: jhipster-migrate
    defaults:
      run:
        working-directory: ${{ github.workspace }}/app
    name: ${{ matrix.tests }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: jhipster/actions/create-app-path@v0
      - uses: jhipster/actions/setup-git@v0
      - uses: actions/checkout@v4
        with:
          path: generator-jhipster-migrate
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: ${{ matrix.generate-command }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm ci
          npm link
        working-directory: ${{ github.workspace }}/generator-jhipster-migrate
      - run: ${{ matrix.migrate-command }}
      - run: git -c color.ui=always diff @^
